name: Build Test

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
env:
  BUILD_TYPE: Release

jobs:
  build-webos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Download ares-cli-rs
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "webosbrew/ares-cli-rs"
          latest: true
          fileName: "ares-package_*.deb"
          out-file-path: "temp"

      - name: Download Homebrew Toolbox
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "webosbrew/dev-toolbox-cli"
          latest: true
          fileName: "webosbrew-toolbox-*.deb"
          out-file-path: "temp"

      - name: Install Tools
        run: sudo apt-get install ./temp/*.deb

      - name: Download webOS NDK
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "openlgtv/buildroot-nc4"
          tag: "webos-b17b4cc"
          fileName: "arm-webos-linux-gnueabi_sdk-buildroot.tar.gz"
          out-file-path: "/tmp"

      - name: Extract webOS NDK
        shell: bash
        working-directory: /tmp
        run: |
          tar xzf arm-webos-linux-gnueabi_sdk-buildroot.tar.gz
          ./arm-webos-linux-gnueabi_sdk-buildroot/relocate-sdk.sh

      - name: Build
        env:
          TOOLCHAIN_FILE: /tmp/arm-webos-linux-gnueabi_sdk-buildroot/usr/share/buildroot/toolchainfile.cmake
        run: ./tools/webos/easy_build.sh -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Add Commit Hash Suffix
        shell: bash
        working-directory: dist
        run: for file in *.ipk ; do mv $file ${file//_arm/-${GITHUB_SHA:0:8}_arm} ; done

      - uses: actions/upload-artifact@v4
        with:
          name: webos-snapshot
          path: dist/*.ipk

      - name: Compatibility Check
        run: webosbrew-ipk-verify -f markdown -d -o $GITHUB_STEP_SUMMARY dist/*.ipk
